### ISSUE TITLE
Disclaimers/gotchas to watch out for poor performace (same class predicted for every input)

### ISSUE THREAD

**Issue by ada-nai** [UKPLab/AdaSent#2]
Hello to the authors/maintainers

I am trying to implement AdaSent on custom data. I followed the steps mentioned in the README and also experimented with a few hyper-parameters across the three training scripts as provided in the `argparse`  variables.

While I am getting outputs for external texts on inference (via SetFitModel.from_pretrained(<locally_trained_model_path>) ), one thing I am observing is that the same class is predicted, no matter what I provide as input.

I have ensured that the same base PLM (`distilroberta-base`) is used in the DAPT and SEPT modules.

Also, one warning pops up on inference: "There are adapters available but none are activated for the forward pass." 
(in `transformers/adapters/model_mixin`)

How do I ensure that the adapters are activated, this is also a potential reason for poor inference, perhaps?

Any guidance/suggestions on the above query would be helpful. 

Thank you again to all contributors for the detailed presentation of information!

**Comment by tbst730** [comment]
Hello Adarsh, thanks for your interest in our work! 

Yes, the adapter should be activated for the inference, you can do it similarly as in the training script (line 131 activates the adapter):  https://github.com/UKPLab/AdaSent/blob/d11b9668be5e02e2343588b31e4b39e0d54dcf04/scripts/SetFit/train_setfit.py#L126-L144

If you are loading a trained SetFit model using `SetFitModel.from_pretrained(<locally_trained_model_path>)`, you can activate the adapter by ```setfit_model.model_body[0].auto_model.set_active_adapters(args.adapter_name)```, where `model_body[0]` is the `word_embedding_model` in the training script. 

I hope this information can help. Please feel free to contact us if you have further questions!

**Comment by ada-nai** [comment]
The inference flow works now after following your suggestion, thank you very much!

I need to revisit the paper again. My understanding was that the adapter weights are "infused" post the SetFit training and it now handles the inputs implicitly. 

I am relatively new to understanding and applying papers, so still learning, but thanks to awesome folks in the community who are there to guide us. We stand on your humble shoulders. 

I know I might have more queries, and will reach out. vielen danke!

**Comment by ada-nai** [comment]
One suggestion I want to provide is that the adapter activation nudge can be provided in the model README generated after SetFit training in the `Usage` section

## Usage

You can then run inference as follows:

```python
from setfit import SetFitModel

# Download from Hub and run inference
model = SetFitModel.from_pretrained("models/<trained_model_folder_path>")

**# activate adasent adapter post model loading
# fetch adapter_name from sept `adapter_config`
model.model_body[0].auto_model.set_active_adapters(adapter_name)**

# Run inference
preds = model(["i loved the spiderman movie!", "pineapple on pizza is the worst 🤮"])
```

**Comment by tbst730** [comment]
Thanks for your great suggestions! I have added the inference code to the README. 

Our code saves the adapter with the SetFitModel model body, but does not automatically activate it during inference. The paper does not describe every detail, but I should have made it explicit in the codebase, sorry for the confusion caused!

**Comment by ada-nai** [comment]
Thank you again, I will reach out in case of more queries. 🤗

**Comment by Martin-Ndlovu** [comment]
Hey guys, can anyone help. I'm always getting this error **There are adapters available but none are activated for the forward pass**.

````
import torch
from transformers import AutoTokenizer, BitsAndBytesConfig

from datasets import load_dataset
import math
from bert_score import score
from adapters import AutoAdapterModel
import os


# -----------------------------
# Paths
# -----------------------------
base_model_name = "models/Llama-3.2-1B"          
adapter_path    = "output/llama-3.2-alpaca-sft"  # path where LoRA adapter was saved
# adapter_name = "alpaca_adapter"

os.environ["CUDA_VISIBLE_DEVICES"] = "0" 
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# -----------------------------
# Load base model in 4-bit
# -----------------------------
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
)

print("Loading base model...")
base_model = AutoAdapterModel.from_pretrained(
    base_model_name,
    # quantization_config=bnb_config,
    # device_map="auto",
    trust_remote_code=True,
)
base_model.config.use_cache = True  # for inference
# base_model.to(device)

# Load LoRA adapter with adapters library
print("Loading LoRA adapter...")
adapter_name = base_model.load_adapter(
    adapter_path,
    config = "lora",
    set_active=True,
    load_as="alpaca_adapter")
base_model.set_active_adapters(adapter_name)
base_model.eval()
model = base_model
model.to(device)```
